on:
  push:
    branches: [ master ]
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: chrislennon/action-aws-cli@v1.1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Deploy
        run: aws s3 sync dist/ s3://activity-timer --acl public-read
      - name: Clear CF cache
        run: aws cloudfront create-invalidation --distribution-id E3PJH9TOPHL4ZJ --paths "/index.html"
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}