on:
  push:
    branches: [ develop ]
name: Deploy develop branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: chrislennon/action-aws-cli@v1.1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build-develop
      - name: Deploy
        run: aws s3 sync dist/ s3://activity-timer-develop --acl public-read
      - name: Clear CF cache
        run: aws cloudfront create-invalidation --distribution-id E2MS8GHZWJZE05 --paths "/index.html" "/card_back_section.html" "/history.html" "/change_estimate.html" "/settings.html" "/notifications.html"
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}