on:
  push:
    branches: [ feature/v2 ]
name: Deploy v2 - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
        env:
          ACT_ENV: 'dev'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-1'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: cdk deploy
        run: cd infrastructure && yarn install && ACT_ENV=dev yarn cdk deploy --require-approval never